# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  platformer_proto_config = debug

else ifeq ($(config),release)
  platformer_proto_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := platformer-proto

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

platformer-proto:
ifneq (,$(platformer_proto_config))
	@echo "==== Building platformer-proto ($(platformer_proto_config)) ===="
	@${MAKE} --no-print-directory -C . -f platformer-proto.make config=$(platformer_proto_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f platformer-proto.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   platformer-proto"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"