# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tetris_proto_config = debug

else ifeq ($(config),release)
  tetris_proto_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := tetris-proto

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tetris-proto:
ifneq (,$(tetris_proto_config))
	@echo "==== Building tetris-proto ($(tetris_proto_config)) ===="
	@${MAKE} --no-print-directory -C . -f tetris-proto.make config=$(tetris_proto_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tetris-proto.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tetris-proto"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"