# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tetrush_config = debug

else ifeq ($(config),release)
  tetrush_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := tetrush

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tetrush:
ifneq (,$(tetrush_config))
	@echo "==== Building tetrush ($(tetrush_config)) ===="
	@${MAKE} --no-print-directory -C . -f tetrush.make config=$(tetrush_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tetrush.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tetrush"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"